export const COUNTRIES = [
  { name: "Afghanistan",            code: "AF", phone: "+93"   },
  { name: "Albania",                code: "AL", phone: "+355"  },
  { name: "Algeria",                code: "DZ", phone: "+213"  },
  { name: "Argentina",              code: "AR", phone: "+54"   },
  { name: "Australia",              code: "AU", phone: "+61"   },
  { name: "Austria",                code: "AT", phone: "+43"   },
  { name: "Belgium",                code: "BE", phone: "+32"   },
  { name: "Bolivia",                code: "BO", phone: "+591"  },
  { name: "Brazil",                 code: "BR", phone: "+55"   },
  { name: "Cambodia",               code: "KH", phone: "+855"  },
  { name: "Canada",                 code: "CA", phone: "+1"    },
  { name: "Chile",                  code: "CL", phone: "+56"   },
  { name: "China",                  code: "CN", phone: "+86"   },
  { name: "Colombia",               code: "CO", phone: "+57"   },
  { name: "Costa Rica",             code: "CR", phone: "+506"  },
  { name: "Cuba",                   code: "CU", phone: "+53"   },
  { name: "Denmark",                code: "DK", phone: "+45"   },
  { name: "Dominican Republic",     code: "DO", phone: "+1-809"},
  { name: "Ecuador",                code: "EC", phone: "+593"  },
  { name: "Egypt",                  code: "EG", phone: "+20"   },
  { name: "El Salvador",            code: "SV", phone: "+503"  },
  { name: "Ethiopia",               code: "ET", phone: "+251"  },
  { name: "Finland",                code: "FI", phone: "+358"  },
  { name: "France",                 code: "FR", phone: "+33"   },
  { name: "Germany",                code: "DE", phone: "+49"   },
  { name: "Ghana",                  code: "GH", phone: "+233"  },
  { name: "Greece",                 code: "GR", phone: "+30"   },
  { name: "Guatemala",              code: "GT", phone: "+502"  },
  { name: "Honduras",               code: "HN", phone: "+504"  },
  { name: "Hungary",                code: "HU", phone: "+36"   },
  { name: "India",                  code: "IN", phone: "+91"   },
  { name: "Indonesia",              code: "ID", phone: "+62"   },
  { name: "Iran",                   code: "IR", phone: "+98"   },
  { name: "Iraq",                   code: "IQ", phone: "+964"  },
  { name: "Ireland",                code: "IE", phone: "+353"  },
  { name: "Israel",                 code: "IL", phone: "+972"  },
  { name: "Italy",                  code: "IT", phone: "+39"   },
  { name: "Jamaica",                code: "JM", phone: "+1-876"},
  { name: "Japan",                  code: "JP", phone: "+81"   },
  { name: "Jordan",                 code: "JO", phone: "+962"  },
  { name: "Kenya",                  code: "KE", phone: "+254"  },
  { name: "Lebanon",                code: "LB", phone: "+961"  },
  { name: "Malaysia",               code: "MY", phone: "+60"   },
  { name: "Mexico",                 code: "MX", phone: "+52"   },
  { name: "Morocco",                code: "MA", phone: "+212"  },
  { name: "Netherlands",            code: "NL", phone: "+31"   },
  { name: "New Zealand",            code: "NZ", phone: "+64"   },
  { name: "Nicaragua",              code: "NI", phone: "+505"  },
  { name: "Nigeria",                code: "NG", phone: "+234"  },
  { name: "Norway",                 code: "NO", phone: "+47"   },
  { name: "Pakistan",               code: "PK", phone: "+92"   },
  { name: "Panama",                 code: "PA", phone: "+507"  },
  { name: "Paraguay",               code: "PY", phone: "+595"  },
  { name: "Peru",                   code: "PE", phone: "+51"   },
  { name: "Philippines",            code: "PH", phone: "+63"   },
  { name: "Poland",                 code: "PL", phone: "+48"   },
  { name: "Portugal",               code: "PT", phone: "+351"  },
  { name: "Puerto Rico",            code: "PR", phone: "+1-787"},
  { name: "Romania",                code: "RO", phone: "+40"   },
  { name: "Russia",                 code: "RU", phone: "+7"    },
  { name: "Saudi Arabia",           code: "SA", phone: "+966"  },
  { name: "Senegal",                code: "SN", phone: "+221"  },
  { name: "South Africa",           code: "ZA", phone: "+27"   },
  { name: "South Korea",            code: "KR", phone: "+82"   },
  { name: "Spain",                  code: "ES", phone: "+34"   },
  { name: "Sweden",                 code: "SE", phone: "+46"   },
  { name: "Switzerland",            code: "CH", phone: "+41"   },
  { name: "Taiwan",                 code: "TW", phone: "+886"  },
  { name: "Thailand",               code: "TH", phone: "+66"   },
  { name: "Trinidad and Tobago",    code: "TT", phone: "+1-868"},
  { name: "Tunisia",                code: "TN", phone: "+216"  },
  { name: "Turkey",                 code: "TR", phone: "+90"   },
  { name: "Ukraine",                code: "UA", phone: "+380"  },
  { name: "United Arab Emirates",   code: "AE", phone: "+971"  },
  { name: "United Kingdom",         code: "GB", phone: "+44"   },
  { name: "United States",          code: "US", phone: "+1"    },
  { name: "Uruguay",                code: "UY", phone: "+598"  },
  { name: "Venezuela",              code: "VE", phone: "+58"   },
  { name: "Vietnam",                code: "VN", phone: "+84"   },
  { name: "Other",                  code: "XX", phone: "+"     },
] as const;

export type Country = typeof COUNTRIES[number];

export function getPhoneByCountry(name: string): string {
  const found = COUNTRIES.find(c => c.name === name);
  return found?.phone ?? "";
}